

export const KG1Rice: any = [
  {
    CodeName: 'JG1',
    FullName: 'Jasmine Rice 20 x 1kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bales: 20,
    Qty_bags_ton: 1000,
  },
  {
    CodeName: 'A1',
    FullName: 'Super A1 20 x 1kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bales: 20,
    Qty_bales_ton: 50,
    Qty_bags_ton: 1000,
  },
  {
    CodeName: 'SW1',
    FullName: 'Sweet Rice 20 x 1kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'S1',
    FullName: 'Star Rice 20 x 1 Kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'JB1',
    FullName: 'Brown rice 20 x 1kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'F1',
    FullName: 'Frangipani rice 20 X 1kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'JR1',
    FullName: 'Jasmine Red rice 20x1 kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
];

export const KG5Rice: any = [
  {
    CodeName: 'JG5',
    FullName: 'Jasmine Rice 4 x 5kg',
    Color: '',
    Weight: 5,
    Uom: 'KG',
    Qty_in_bale: 4,
    Qty_in_ton: 200,
  },
  {
    CodeName: 'A5',
    FullName: 'Super A1 4 x 5kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'S5',
    FullName: 'Star Rice 4 x 5kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'F5',
    FullName: 'Frangipani rice 4 X 5 kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'JR5',
    FullName: 'Jasmine Red rice 4x5 kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
];

export const KG10Rice: any = [
  {
    CodeName: 'JG10',
    FullName: 'Jasmine Rice 10 kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 100,
  },
  {
    CodeName: 'A10',
    FullName: 'Super A1 10kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'S10',
    FullName: 'Star Rice 10kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'JB10',
    FullName: 'Brown rice 10kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'F10',
    FullName: 'Frangipani rice 10kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'JR10',
    FullName: 'Jasmine Red rice 10 kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
];

export const KG20Rice: any = [
  {
    CodeName: 'S20',
    FullName: 'Star Rice 20kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
  {
    CodeName: 'JB20',
    FullName: 'Brown rice 20kg',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 20,
  },
];

export const Salt: any = [
  {
    CodeName: 'SA250',
    FullName: 'Star salt 250G',
    Color: '',
    Weight: 250,
    Uom: 'G',
    Qty_in_bale: 80,
    Qty_in_ton: 4000,
  },
  {
    CodeName: 'SA500',
    FullName: 'Star salt 500G',
    Color: '',
    Weight: 500,
    Uom: 'G',
    Qty_in_bale: 40,
    Qty_in_ton: 2000,
  },
  {
    CodeName: 'SA1KG',
    FullName: 'Star salt 1KG',
    Color: '',
    Weight: 1,
    Uom: 'KG',
    Qty_in_bale: 20,
    Qty_in_ton: 1000,
  },
];


export const LunchBox: any = [
  {
    CodeName: 'Lunchbox - 105P',
    FullName: 'Lunchbox - 105P',
    Color: '',
    Weight: 0,
    Uom: 'G',
    // Qty_in_bale: 80,
    // Qty_in_ton: 4000,
  },
];
